server:
  port: 9020
  
spring:
  application:
    name: api-gateway-ms
    
  cloud:
    gateway:
      routes:
      - id: customer-ms
        uri: lb://customer-ms
        predicates:
        - Path= /customer/**
        
      - id: product-ms
        uri: lb://product-ms
        predicates:
        - Path= /product/**
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
